[package]
name = "pong_fe_glium"
version = "0.1.0"
authors = ["Danny Fritz <dannyfritz@gmail.com>"]

[dependencies]
pong_lib = { path = "../pong_lib" }
glium = "*"
nalgebra = "0.14"
time = "0.1.39"
rodio = "0.7"
